import type { ScanRecord } from './types';

export const SEED_HISTORY: ScanRecord[] = [
  {
    id: 'seed-1',
    date: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
    label: 'Bank impersonation email',
    type: 'EMAIL',
    score: 94,
    level: 'HIGH',
    preview: 'URGENT: Your bank account will be suspended today. Verify your account immediately...',
    categories: ['social-engineering', 'credential'],
  },
  {
    id: 'seed-2',
    date: new Date(Date.now() - 1000 * 60 * 60 * 6).toISOString(),
    label: 'UPI prize scam',
    type: 'MESSAGE',
    score: 88,
    level: 'HIGH',
    preview: 'Congratulations! You have won ₹50,00,000 in our lucky draw. Pay ₹2,999 processing fee...',
    categories: ['financial', 'social-engineering'],
  },
  {
    id: 'seed-3',
    date: new Date(Date.now() - 1000 * 60 * 60 * 26).toISOString(),
    label: 'Suspicious login alert',
    type: 'EMAIL',
    score: 72,
    level: 'MEDIUM',
    preview: 'We detected a suspicious login attempt. Verify it was you by clicking this link...',
    categories: ['social-engineering', 'url'],
  },
  {
    id: 'seed-4',
    date: new Date(Date.now() - 1000 * 60 * 60 * 30).toISOString(),
    label: 'Fake courier delivery',
    type: 'URL',
    score: 81,
    level: 'HIGH',
    preview: 'http://track-parcel-urgent.xyz/verify?ref=IN8842 — your package is on hold. Confirm address.',
    categories: ['url', 'financial'],
  },
  {
    id: 'seed-5',
    date: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(),
    label: 'OTP harvesting',
    type: 'MESSAGE',
    score: 97,
    level: 'CRITICAL',
    preview: 'Your account has been selected for verification. Send the OTP to our support representative...',
    categories: ['credential', 'social-engineering'],
  },
  {
    id: 'seed-6',
    date: new Date(Date.now() - 1000 * 60 * 60 * 52).toISOString(),
    label: 'KYC verification scam',
    type: 'MESSAGE',
    score: 79,
    level: 'HIGH',
    preview: 'Your KYC is pending. Update your details immediately to avoid account closure. Click here...',
    categories: ['social-engineering', 'credential'],
  },
  {
    id: 'seed-7',
    date: new Date(Date.now() - 1000 * 60 * 60 * 70).toISOString(),
    label: 'Investment offer',
    type: 'MESSAGE',
    score: 76,
    level: 'HIGH',
    preview: 'Double your money in 7 days. Guaranteed returns. Invest ₹10,000 today, limited seats.',
    categories: ['financial', 'social-engineering'],
  },
  {
    id: 'seed-8',
    date: new Date(Date.now() - 1000 * 60 * 60 * 96).toISOString(),
    label: 'Verified notification',
    type: 'MESSAGE',
    score: 5,
    level: 'SAFE',
    preview: 'Your electricity bill of ₹1,240 is due on 20 August. Pay through the official app.',
    categories: [],
  },
];
